version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: milog-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: milog-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: milog
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/01_users.sql:/docker-entrypoint-initdb.d/01_users.sql
      - ./mysql/02_vehicles.sql:/docker-entrypoint-initdb.d/02_vehicles.sql
      - ./mysql/03_fuel_logs.sql:/docker-entrypoint-initdb.d/03_fuel_logs.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: milog-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
